# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/dbpool

    - name: Test
      run: go test -v ./...
      
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Upload binary
        path: bin/dbpool

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/dbpool
